/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShutdownRouteImport } from './routes/shutdown'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamilyVisionRouteImport } from './routes/family-vision'
import { Route as DebtCalculatorRouteImport } from './routes/debt-calculator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as BrotherhoodRouteImport } from './routes/brotherhood'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum/index'
import { Route as ApiSetupRouteImport } from './routes/api.setup'
import { Route as CurriculumModuleIdIndexRouteImport } from './routes/curriculum/$moduleId/index'
import { Route as CurriculumModuleIdLessonIdIndexRouteImport } from './routes/curriculum/$moduleId/$lessonId/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShutdownRoute = ShutdownRouteImport.update({
  id: '/shutdown',
  path: '/shutdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyVisionRoute = FamilyVisionRouteImport.update({
  id: '/family-vision',
  path: '/family-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtCalculatorRoute = DebtCalculatorRouteImport.update({
  id: '/debt-calculator',
  path: '/debt-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const BrotherhoodRoute = BrotherhoodRouteImport.update({
  id: '/brotherhood',
  path: '/brotherhood',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumModuleIdIndexRoute = CurriculumModuleIdIndexRouteImport.update({
  id: '/curriculum/$moduleId/',
  path: '/curriculum/$moduleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumModuleIdLessonIdIndexRoute =
  CurriculumModuleIdLessonIdIndexRouteImport.update({
    id: '/curriculum/$moduleId/$lessonId/',
    path: '/curriculum/$moduleId/$lessonId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brotherhood': typeof BrotherhoodRoute
  '/challenges': typeof ChallengesRoute
  '/dashboard': typeof DashboardRoute
  '/debt-calculator': typeof DebtCalculatorRoute
  '/family-vision': typeof FamilyVisionRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/shutdown': typeof ShutdownRoute
  '/signup': typeof SignupRoute
  '/api/setup': typeof ApiSetupRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/curriculum/$moduleId/': typeof CurriculumModuleIdIndexRoute
  '/curriculum/$moduleId/$lessonId/': typeof CurriculumModuleIdLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brotherhood': typeof BrotherhoodRoute
  '/challenges': typeof ChallengesRoute
  '/dashboard': typeof DashboardRoute
  '/debt-calculator': typeof DebtCalculatorRoute
  '/family-vision': typeof FamilyVisionRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/shutdown': typeof ShutdownRoute
  '/signup': typeof SignupRoute
  '/api/setup': typeof ApiSetupRoute
  '/curriculum': typeof CurriculumIndexRoute
  '/curriculum/$moduleId': typeof CurriculumModuleIdIndexRoute
  '/curriculum/$moduleId/$lessonId': typeof CurriculumModuleIdLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brotherhood': typeof BrotherhoodRoute
  '/challenges': typeof ChallengesRoute
  '/dashboard': typeof DashboardRoute
  '/debt-calculator': typeof DebtCalculatorRoute
  '/family-vision': typeof FamilyVisionRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/shutdown': typeof ShutdownRoute
  '/signup': typeof SignupRoute
  '/api/setup': typeof ApiSetupRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/curriculum/$moduleId/': typeof CurriculumModuleIdIndexRoute
  '/curriculum/$moduleId/$lessonId/': typeof CurriculumModuleIdLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brotherhood'
    | '/challenges'
    | '/dashboard'
    | '/debt-calculator'
    | '/family-vision'
    | '/login'
    | '/resources'
    | '/shutdown'
    | '/signup'
    | '/api/setup'
    | '/curriculum/'
    | '/curriculum/$moduleId/'
    | '/curriculum/$moduleId/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brotherhood'
    | '/challenges'
    | '/dashboard'
    | '/debt-calculator'
    | '/family-vision'
    | '/login'
    | '/resources'
    | '/shutdown'
    | '/signup'
    | '/api/setup'
    | '/curriculum'
    | '/curriculum/$moduleId'
    | '/curriculum/$moduleId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/brotherhood'
    | '/challenges'
    | '/dashboard'
    | '/debt-calculator'
    | '/family-vision'
    | '/login'
    | '/resources'
    | '/shutdown'
    | '/signup'
    | '/api/setup'
    | '/curriculum/'
    | '/curriculum/$moduleId/'
    | '/curriculum/$moduleId/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrotherhoodRoute: typeof BrotherhoodRoute
  ChallengesRoute: typeof ChallengesRoute
  DashboardRoute: typeof DashboardRoute
  DebtCalculatorRoute: typeof DebtCalculatorRoute
  FamilyVisionRoute: typeof FamilyVisionRoute
  LoginRoute: typeof LoginRoute
  ResourcesRoute: typeof ResourcesRoute
  ShutdownRoute: typeof ShutdownRoute
  SignupRoute: typeof SignupRoute
  ApiSetupRoute: typeof ApiSetupRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
  CurriculumModuleIdIndexRoute: typeof CurriculumModuleIdIndexRoute
  CurriculumModuleIdLessonIdIndexRoute: typeof CurriculumModuleIdLessonIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shutdown': {
      id: '/shutdown'
      path: '/shutdown'
      fullPath: '/shutdown'
      preLoaderRoute: typeof ShutdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-vision': {
      id: '/family-vision'
      path: '/family-vision'
      fullPath: '/family-vision'
      preLoaderRoute: typeof FamilyVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debt-calculator': {
      id: '/debt-calculator'
      path: '/debt-calculator'
      fullPath: '/debt-calculator'
      preLoaderRoute: typeof DebtCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brotherhood': {
      id: '/brotherhood'
      path: '/brotherhood'
      fullPath: '/brotherhood'
      preLoaderRoute: typeof BrotherhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$moduleId/': {
      id: '/curriculum/$moduleId/'
      path: '/curriculum/$moduleId'
      fullPath: '/curriculum/$moduleId/'
      preLoaderRoute: typeof CurriculumModuleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$moduleId/$lessonId/': {
      id: '/curriculum/$moduleId/$lessonId/'
      path: '/curriculum/$moduleId/$lessonId'
      fullPath: '/curriculum/$moduleId/$lessonId/'
      preLoaderRoute: typeof CurriculumModuleIdLessonIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrotherhoodRoute: BrotherhoodRoute,
  ChallengesRoute: ChallengesRoute,
  DashboardRoute: DashboardRoute,
  DebtCalculatorRoute: DebtCalculatorRoute,
  FamilyVisionRoute: FamilyVisionRoute,
  LoginRoute: LoginRoute,
  ResourcesRoute: ResourcesRoute,
  ShutdownRoute: ShutdownRoute,
  SignupRoute: SignupRoute,
  ApiSetupRoute: ApiSetupRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
  CurriculumModuleIdIndexRoute: CurriculumModuleIdIndexRoute,
  CurriculumModuleIdLessonIdIndexRoute: CurriculumModuleIdLessonIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
